
eureka:
  client:
    service-url:
      defaultZone: http://peer-1-server.com:9001/eureka, http://peer-2-server.com:9002/eureka, http://peer-3-server.com:9003/eureka
spring:
  application:
    name: eureka-client-service
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    web:
      server:
        request:
          autotime:
            percentiles: 0.90,0.95,0.99
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true
  endpoints:
    prometheus:
      enabled: true
      path: /metrics
    web:
      exposure:
        include: health,info,metrics,prometheus
  health:
    mail:
      enabled: false